palmetto/palm-cli

README.md

Add link to hosted documentation!

Add link to documentation site

---

setup.py

Package name was not updated, needs to be palm-cli so we can upload to Pypi

Oops - needed to update the package name!

---

docs/source/commands.rst

- [ X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
A description of the problem you're trying to solve.
Any relevant logs, error output, etc.
An overview of the suggested solution
If the feature changes current behavior, reasons why your solution is better.
When attempting a jaffleshop demo, I noted that the documentation for scaffolding commands and command groups needed revision.
…
…
**Operating System:** …
**Platform:** …
**Target Platform:** …

fix scaffold docs

---

palm/plugins/core/commands/cmd_update.py

Update implementation of palm upgrade to use the palm pypi package instead of the legacy github installation

Palm upgrade from pypi

---

palm/plugins/core/commands/cmd_shell.py

This allows users to shell into their container and run arbitrary commands. Useful for power users who need direct access to their underlying CLIs and for debugging problems inside of the container
DATA-477
…
**Operating System:** mac OS

DATA-477: Add palm shell command

---

.github/workflows/pull_request.yaml
palm/cli.py
palm/plugins/base.py
palm/plugins/core/core_plugin.py
palm/plugins/repo/repo_plugin.py
palm/plugins/test_internal/test_internal_plugin.py
palm/utils.py

Add a GH action job to lint code on PRs

Add job to lint on pull request

---

docs/source/commands.rst
palm/cli.py

Sometimes you don't want to see all the commands
#34

Add ability to exclude palm commands from a project's config

---

palm/cli.py
palm/plugins/core/core_plugin.py
palm/plugins/repo/repo_plugin.py
palm/plugins/test_internal/test_internal_plugin.py
palm/utils.py
tests/unit/test_utils.py

This test signature was somehow missed and got merged? 
correcting it. Probably before the CI PR went in. 
A description of the problem you're trying to solve.
Test needs to correctly look for capture_output behavior. 
**Operating System:**MacOS
**Platform:**Monterey
**Target Platform:**python3.6 + python3.9

OOOPS! Somehow this got missed.

---

docs/source/index.rst
docs/source/introduction/examples.rst
docs/source/introduction/viewpoint.rst

Added examples of palm use to the docs, and a viewpoint statement. 
Nope
This is a living, growing document and should continue to evolve as we understand palm better. 
**Operating System:** MacOs
**Platform:** Catalina
**Target Platform:** All (readthedocs web)

Add Examples to Docs

---

CHANGELOG.md

We needed a changelog for 2.1.0!
…
…

Adding changelog for v2.1.0

---

.github/workflows/pull_request.yaml

We need to be sure palm works in multiple supported versions of python

Update test job to run against matrix of python versions

---

.github/CODEOWNERS

No functional change, additional code owners

Add Corey and Olivia as code owners

---

docs/source/plugins.rst
palm/palm_config.py
requirements.txt
tests/unit/test_palm_config.py

Adds the ability to configure global plugins which will work across all repositories.
No, but we've talked about this a lot
This will pair well with palm-workflow (internal palm plugin at Palmetto)
**Operating System:**  Mac OS only

[FEATURE] Global plugins

---

palm/palm_config.py
tests/conftest.py

This allows plugin and application commands to use the Repository object as needed

Make the pygit2 repository available via palm config

---

.github/workflows/pull_request.yaml
dev-requirements.txt
requirements.txt

The version of `black` we were pinned to had an issue with the latest version of click, this change resolves that error.

[HOTFIX] Upgrade black to latest version to prevent errors in CI

---

palm/cli.py
palm/code_generator.py
palm/plugin_manager.py
palm/plugins/core/commands/cmd_init.py
palm/plugins/core/create_files.py
setup.py
tests/conftest.py
tests/unit/test_cli.py
tests/unit/test_plugin_manager.py

Resolve CodeQL errors relating to imports
- remove missing imports
- resolve double import of importlib
Resolves multiple CodeQL errors

[CHORE] Cleanup import errors from CodeQL

---

palm/environment.py

Add explicit return to improve code readability
Resolves an error from CodeQL

[CHORE] Consistent explicit returns

---

palm/plugins/core/commands/cmd_init.py

Use Path.touch instead of chaining open/close without using context manager
- this is a more reliable implementation of the same thing
Resolves error detected by CodeQL

[CHORE] Resolve file not always closed

---

.github/CODEOWNERS

Mariah and Evan are code owners, Ethan Emily and Corey are no longer active with palmetto accounts.
N/A

[CHORE] Update codeowners

---

.github/workflows/pull_request.yaml
.github/workflows/pypi-deploy.yaml
CHANGELOG.md

New Github action workflow that:
- Runs when a v* tag is pushed to main
- Confirms version was bumped in setup.py
- Reads the changelog
- Builds the package
- Creates a release
- Publishes to pypi
Update the format of the changelog for automation using the "keep a changelog" format
N/A
This is untested, but I think it will work... may need to push hotfixes around the time of the next release.

[FEATURE] CD workflow

---

.github/workflows/pypi-deploy.yaml
CHANGELOG.md
docs/source/code-generation.rst

Let's try that again, shall we?

[Release] v2.5.0

---

requirements.txt

Remove upper version pin, code already supports pyyaml 6

[FEATURE] Support for pyyaml 6

---

palm/environment.py

This has been marked as deprecated for a long time. I have not seen that deprecation warning in recent memory. Should be safe to remove this.
No, just cleaning up.

Removes run_in_shell
